import './globals.css'
import { Inter } from 'next/font/google'
import vasirFont from '../constants/localFonts'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${vasirFont.variable} font-sans`}>{children}</body>
    </html>
  )
}
